name: Windows

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Set Env Var
        run: echo MY_ENV_VAR=abc >> $env:GITHUB_ENV
      - name: Get Env Var
        run: echo $env:MY_ENV_VAR
